# This file defines how to build and run your application with Docker Compose.
services:
  frontend:
    build:
      context: .
      args:
        # These arguments are read from your .env file during the build process
        - NEXT_PUBLIC_API_HOST
        - NEXT_PUBLIC_API_PORT
        - NEXT_PUBLIC_API_PROTOCOL
        - NEXT_PUBLIC_STATS_API_HOST
        - NEXT_PUBLIC_VISUALIZE_API_HOST
        - NEXT_PUBLIC_APP_HOST
        - NEXT_PUBLIC_APP_PORT
        - NEXT_PUBLIC_APP_INSTANCE
        - NEXT_PUBLIC_APP_ENV
        - NEXT_PUBLIC_APP_PROTOCOL
        - NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL
        - NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID
        - NEXT_PUBLIC_NETWORK_NAME
        - NEXT_PUBLIC_NETWORK_SHORT_NAME
        - NEXT_PUBLIC_NETWORK_ID
        - NEXT_PUBLIC_NETWORK_CURRENCY_NAME
        - NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL
        - NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS
        - NEXT_PUBLIC_NETWORK_RPC_URL
        - NEXT_PUBLIC_NETWORK_LOGO
        - NEXT_PUBLIC_NETWORK_LOGO_DARK
        - NEXT_PUBLIC_NETWORK_ICON
        - NEXT_PUBLIC_NETWORK_ICON_DARK
        - NEXT_PUBLIC_MULTICHAIN_BALANCE_PROVIDER_CONFIG
        - NEXT_PUBLIC_ENABLE_MULTICHAINS
        - NEXT_PUBLIC_HOMEPAGE_CHARTS
        - NEXT_PUBLIC_FOOTER_LINKS
        - NEXT_PUBLIC_GIT_TAG
        - NEXT_PUBLIC_TWITTER_URL
        - NEXT_PUBLIC_TELEGRAM_URL
        - NEXT_PUBLIC_DISCORD_URL
        - NEXT_PUBLIC_OG_IMAGE_URL
        - NEXT_PUBLIC_FAVICON_GENERATOR_API_KEY
        - NEXT_PUBLIC_NAVIGATION_LAYOUT
        - NEXT_PUBLIC_FEATURED_NETWORKS
        - NEXT_PUBLIC_OTHER_LINKS
        - NEXT_PUBLIC_MARKETPLACE_ENABLED
        - NEXT_PUBLIC_SWAP_BUTTON_URL
        - NEXT_PUBLIC_HAS_BEACON_CHAIN
    image: blockscout-frontend:local
    ports:
      - "3000:3000"
    env_file:
      - .env